project_id = "routenote"

[functions.routenote-postcode-zone]
verify_jwt = false

[functions.routenote-geocode]
verify_jwt = false

[functions.routenote-send-push]
verify_jwt = true

[functions.routenote-road-geometry]
verify_jwt = false

[functions.routenote-zone-at-point]
verify_jwt = false
