-- Market seed data (반여농산물시장 점포 데이터)
-- 프리뷰(xrrdokcjhjqdfvwtbenl) 현재 상태에서 추출. building code 로 매칭하여 이전.
-- 동(building) 데이터/테이블은 20260528_market_map.sql 에서 처리됨.

-- 청과물동 (cheonggwamul)
INSERT INTO public.rn_market_stalls
  (building_id, row_idx, col_idx, stall_number, vendor_name, section_name, company_name, cell_type, notes, borders)
SELECT b.id, v.r, v.c, v.sn, v.vn, v.sect, v.co, v.ct, v.nt, v.bd::jsonb
FROM (VALUES
  ('cheonggwamul',1,0,NULL,'동부청과',NULL,'동부청과','company_header',NULL,NULL),
  ('cheonggwamul',1,19,NULL,'부산중앙청과',NULL,'부산중앙청과','company_header',NULL,NULL),
  ('cheonggwamul',1,38,NULL,'농협반여공판장',NULL,'농협반여공판장','company_header',NULL,NULL),
  ('cheonggwamul',4,2,NULL,NULL,'북15','동부청과','section_header',NULL,NULL),
  ('cheonggwamul',4,6,NULL,NULL,'북14','동부청과','section_header',NULL,NULL),
  ('cheonggwamul',4,9,NULL,NULL,'북13','동부청과','section_header',NULL,NULL),
  ('cheonggwamul',4,13,NULL,NULL,'북12','부산중앙청과','section_header',NULL,NULL),
  ('cheonggwamul',4,17,NULL,NULL,'북11','부산중앙청과','section_header',NULL,NULL),
  ('cheonggwamul',4,21,NULL,NULL,'북10','부산중앙청과','section_header',NULL,NULL),
  ('cheonggwamul',4,25,NULL,NULL,'북9','부산중앙청과','section_header',NULL,NULL),
  ('cheonggwamul',4,28,NULL,NULL,'북8','농협반여공판장','section_header',NULL,NULL),
  ('cheonggwamul',4,32,NULL,NULL,'북7','농협반여공판장','section_header',NULL,NULL),
  ('cheonggwamul',4,36,NULL,NULL,'북6','농협반여공판장','section_header',NULL,NULL),
  ('cheonggwamul',4,40,NULL,NULL,'북5','농협반여공판장','section_header',NULL,NULL),
  ('cheonggwamul',4,44,NULL,NULL,'북4','농협반여공판장','section_header',NULL,NULL),
  ('cheonggwamul',4,47,NULL,NULL,'북3','농협반여공판장','section_header',NULL,NULL),
  ('cheonggwamul',4,51,NULL,NULL,'북2','농협반여공판장','section_header',NULL,NULL),
  ('cheonggwamul',4,55,NULL,NULL,'북1','농협반여공판장','section_header',NULL,NULL),
  ('cheonggwamul',5,1,'277',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,3,'129',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,4,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,5,'112',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,7,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,12,'217',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,14,'200',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,15,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,16,'179',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,18,'113',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,19,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,20,'221',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,22,'189',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,23,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,24,'112',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,26,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,31,'210',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,33,'110',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,34,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,35,'286/136',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,37,'123',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,38,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,39,'91',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,41,'8',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,42,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,43,'299',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,45,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,50,'222',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,52,'230',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,53,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,54,'227',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',5,56,'156',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',5,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',6,1,'188',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,3,'111',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,5,'88',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,7,'168',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,12,'141',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,14,'101',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,16,'158',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,18,'202',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,20,'28',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,22,'45',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,24,'177',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,26,'161',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,31,'188',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,33,'179',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,35,'222',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,37,'155',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,39,'43',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,41,'43',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,43,'229',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,45,'235',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,50,'211',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,52,'199/167',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,54,'224',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',6,56,'244',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',6,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,1,'220',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,3,'117',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,5,'123',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,7,'21',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,12,'157',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,14,'9',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,16,'205',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,18,'110',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,20,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,22,'66',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,24,'144',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,26,'143',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,31,'162',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,33,'119',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,35,'132',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,37,'163',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,39,'49',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,41,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,43,'117',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,45,'191',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,50,'136',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,52,'130',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,54,'221',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',7,56,'106',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',7,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,1,'121',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,3,'178',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,5,'40',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,7,'15',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,12,'142',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,14,'96',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,16,'44',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,18,'137',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,20,'180',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,22,'89',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,24,'145/175',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,26,'171',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,31,'113',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,33,'209',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,35,'106',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,37,'108',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,39,'70',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,41,'7',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,43,'169',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,45,'172',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,50,'252',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,52,'193',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,54,'255',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',8,56,'202',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',8,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,1,'138',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,3,'105',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,5,'133',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,7,'55',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,12,'50',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,14,'33',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,16,'131',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,18,'150',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,20,'13/25',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,22,'11/88',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,24,'182',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,26,'141',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,31,'109',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,33,'117',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,35,'125',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,37,'138',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,39,'63',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,41,'21',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,43,'154',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,45,'113',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,50,'241/234',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,52,'159',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,54,'200',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',9,56,'277',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',9,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,1,'199',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,3,'169',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,5,'177',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,7,'38',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,12,'11',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,14,'16',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,16,'30',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,18,'20,7',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,20,'18',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,22,'63',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,24,'147',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,26,'158',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,31,'127',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,33,'140',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,35,'200',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,37,'122',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,39,'89',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,41,'59',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,43,'182',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,45,'185',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,50,'150',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,52,'131',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,54,'231',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',10,56,'233',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',10,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,1,'185',NULL,'북15','동부청과','stall',NULL,'{"b": 1, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,3,'172',NULL,'북15','동부청과','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,4,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,5,'27',NULL,'북14','동부청과','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,7,'31',NULL,'북14','동부청과','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,12,'66',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,14,'28',NULL,'북12','부산중앙청과','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,15,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,16,'73',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,18,'5',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,19,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,20,'34',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,22,'15',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,23,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,24,'120',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,26,'107',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,31,'133',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,33,'169',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,34,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,35,'148',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,37,'101',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,38,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,39,'88',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,41,'58',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,42,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,43,'196',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,45,'290',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,50,'111',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,52,'158',NULL,'북2','농협반여공판장','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,53,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,54,'112',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',11,56,'147',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',11,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',13,1,'191',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,3,'109',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,4,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,5,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,7,'45',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,12,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,14,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,15,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,16,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,18,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,19,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,20,'166',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,22,'44',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,23,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,24,'195',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,26,'190',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,31,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,33,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,34,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,35,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,37,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,38,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,39,'60',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,41,'15',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,42,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,43,'1',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,45,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,50,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,52,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,53,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,54,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',13,56,'123',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 1}'::jsonb),
  ('cheonggwamul',13,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 1}'::jsonb),
  ('cheonggwamul',14,1,'114',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,3,'120',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,5,'6',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,7,'250',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,12,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,14,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,16,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,18,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,20,'73',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,22,'78',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,24,'75',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,26,'116',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,31,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,33,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,35,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,37,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,39,'20',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,41,'36',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,43,'71',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,45,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,50,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,52,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,54,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',14,56,'141',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',14,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,1,'196',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,3,'106',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,5,'3',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,7,'17',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,12,NULL,'화장실','북12','부산중앙청과','facility',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,14,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,16,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,18,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,20,'42',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,22,'30',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,24,'43',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,26,'39',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,31,NULL,'화장실','북7','농협반여공판장','facility',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,33,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,35,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,37,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,39,'30/38',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,41,'33',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,43,'37',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,45,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,50,NULL,'화장실','북2','농협반여공판장','facility',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,52,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,54,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',15,56,'122',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',15,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,1,'118',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,3,'189',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,5,'39',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,7,'79',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,11,NULL,'2F','북13','동부청과','facility',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,12,NULL,'계단','북12','부산중앙청과','facility',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,14,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,16,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,18,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,20,'56',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,22,'79/7',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,24,'3',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,26,'102',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,30,NULL,'2F','북8','농협반여공판장','facility',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,31,NULL,'계단','북7','농협반여공판장','facility',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,33,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,35,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,37,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,39,'41',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,41,'52',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,43,'6',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,45,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,49,NULL,'2F','북3','농협반여공판장','facility',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,50,NULL,'계단','북2','농협반여공판장','facility',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,52,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,54,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',16,56,'177',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',16,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,1,'107',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,3,'144',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,5,'48',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,7,'10',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,12,NULL,'매점 1호','북12','부산중앙청과','facility',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,14,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,16,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,18,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,20,'36',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,22,'48',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,24,'7',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,26,'38',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,31,NULL,'매점 2호','북7','농협반여공판장','facility',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,33,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,35,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,37,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,39,'79',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,41,'75',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,43,'5',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,45,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,50,NULL,'매점 3호','북2','농협반여공판장','facility',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,52,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,54,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',17,56,'166',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',17,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,0,'105',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',18,1,'119',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,3,'155',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,5,'80',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,7,'26',NULL,'북14','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,12,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,14,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,16,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,18,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,20,'40',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,22,'69',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,24,'1/90',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,26,'87',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,31,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,33,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,35,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,37,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,39,'26',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,41,'31',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,43,'53',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,45,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,50,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,52,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,54,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',18,56,'137',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',18,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,0,'200',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',19,1,'153',NULL,'북15','동부청과','stall',NULL,'{"b": 1, "l": 1, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,3,'238',NULL,'북15','동부청과','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,4,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,5,'218',NULL,'북14','동부청과','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,7,'152',NULL,'북14','동부청과','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,12,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,14,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,15,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,16,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,18,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,19,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,20,'31',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,22,'5',NULL,'북10','부산중앙청과','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,23,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,24,'22',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,26,'99',NULL,'북9','부산중앙청과','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,30,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,31,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,33,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,34,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,35,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,37,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,38,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,39,'39',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,41,'9',NULL,'북5','농협반여공판장','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,42,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,43,'35',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,45,'35',NULL,'북4','농협반여공판장','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,50,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,52,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,53,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,54,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',19,56,'162',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',19,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',20,1,'144',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',20,3,'112',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',20,4,'106',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',20,5,'218',NULL,'북14','동부청과','stall',NULL,NULL),
  ('cheonggwamul',20,7,'185',NULL,'북14','동부청과','stall',NULL,NULL),
  ('cheonggwamul',20,8,'168',NULL,'북13','동부청과','stall',NULL,NULL),
  ('cheonggwamul',20,11,'10',NULL,'북13','동부청과','stall',NULL,NULL),
  ('cheonggwamul',20,12,'66',NULL,'북12','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',20,14,'45',NULL,'북12','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',20,15,'44',NULL,'북12','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',20,16,'27',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',20,18,'30/15',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',20,19,'36',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',20,20,'9',NULL,'북10','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',20,22,'39',NULL,'북10','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',20,23,'22',NULL,'북10','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',20,24,'31',NULL,'북9','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',20,27,'99',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,30,'199',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,31,'162',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,33,'106',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,34,'163',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,35,'119',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,37,'108',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,38,'8',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,39,'39',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,41,'38',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,43,'49',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,45,'35',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,46,'43',NULL,'북3','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,49,'290/182/211',NULL,'북3','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,52,'150/265',NULL,'북2','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,54,'131/137',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,56,'141',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',20,57,'229',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',20,58,'222',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,0,'113',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',22,1,'238',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',22,3,'196/220',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',22,4,'205',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',22,5,'142',NULL,'북14','동부청과','stall',NULL,NULL),
  ('cheonggwamul',22,7,'129',NULL,'북14','동부청과','stall',NULL,NULL),
  ('cheonggwamul',22,8,'202',NULL,'북13','동부청과','stall',NULL,NULL),
  ('cheonggwamul',22,11,'39',NULL,'북13','동부청과','stall',NULL,NULL),
  ('cheonggwamul',22,12,'96',NULL,'북12','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,15,'9',NULL,'북12','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,16,'48',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,18,'48',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,19,'75',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,20,'18/25',NULL,'북10','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,21,'42',NULL,'북10','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,22,'3',NULL,'북10','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,23,'43',NULL,'북10','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,24,'63',NULL,'북9','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,26,'7',NULL,'북9','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',22,27,'28',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,30,'133',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,32,'182',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,33,'177',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,35,'116',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,38,'127',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,39,'88',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,41,'9',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,45,'58',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,46,'49',NULL,'북3','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,49,'122',NULL,'북3','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,50,'130',NULL,'북2','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,51,'233',NULL,'북2','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,52,'215',NULL,'북2','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,53,'190',NULL,'북2','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,54,'202',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,56,'244',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',22,57,'177',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',22,58,'221',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',23,0,'138',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',23,1,'150',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',23,3,'185',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',23,4,'177',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',23,5,'158',NULL,'북14','동부청과','stall',NULL,NULL),
  ('cheonggwamul',23,7,'199',NULL,'북14','동부청과','stall',NULL,NULL),
  ('cheonggwamul',23,13,'30',NULL,'북12','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',23,14,'40',NULL,'북12','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',23,15,'3',NULL,'북12','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',23,18,'88',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',23,19,'12',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',23,26,'88',NULL,'북9','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',23,27,'44',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,28,'1',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,31,'143',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,32,'140',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,33,'195',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,35,'102',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,36,'132',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,37,'141',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,39,'33',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,40,'38',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,41,'52',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,42,'63',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,43,'26',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,46,'75',NULL,'북3','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,49,'172',NULL,'북3','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,51,'162',NULL,'북2','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,52,'111',NULL,'북2','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,53,'185',NULL,'북2','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',23,57,'235',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',23,58,'227',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',24,0,'191',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',24,1,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',24,3,'110',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',24,7,'155',NULL,'북14','동부청과','stall',NULL,NULL),
  ('cheonggwamul',24,18,'80',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',24,19,'77',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',24,28,'90',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',24,30,'190',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',24,31,'210',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',24,32,'166',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',24,38,'209',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',24,39,'63',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',24,42,'7',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',24,52,'158',NULL,'북2','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',24,53,'166',NULL,'북2','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',24,54,'252',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',24,57,'277',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',24,58,'224',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',25,0,'107',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',25,1,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',25,18,'7',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',25,19,'83',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',25,27,'34',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',25,28,'5',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',25,32,'200',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',25,39,'41',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',25,43,'15',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',25,45,'60',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',25,46,'36',NULL,'북3','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',25,54,'117',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',25,57,'147',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',25,58,'234',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',26,0,'109',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',26,1,'169',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',26,7,'179',NULL,'북14','동부청과','stall',NULL,NULL),
  ('cheonggwamul',26,18,'31',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',26,19,'87',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',26,27,'40',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',26,30,'147',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',26,32,'144',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',26,34,'125',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',26,36,'221',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',26,37,'120',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',26,38,'113',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',26,39,'20',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',26,57,'230',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',26,58,'230',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',27,1,'152',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',27,18,'55',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',27,19,'45',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',27,31,'148',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',27,32,'122',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',27,33,'117',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',27,34,'155',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',27,39,'53',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',27,54,'112',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',27,57,'156',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',27,58,'154',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',28,0,'188',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',28,1,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',28,18,'17',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',28,19,'56',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',28,26,'66',NULL,'북9','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',28,27,'48',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',28,30,'109',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',28,38,'222',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',28,39,'31',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',28,45,'5',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',28,46,'79',NULL,'북3','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',28,54,'159',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',28,57,'200',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',29,1,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',29,18,'6',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',29,19,'78',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',29,27,'79',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',29,30,'158',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',29,39,'6',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',29,45,'75',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',29,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',30,1,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',30,18,'70',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',30,19,'89',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',30,27,'69',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',30,38,'286',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',30,39,'84',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',30,44,'70',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',30,45,'71',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',30,57,'169',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',31,0,'109',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',31,1,'101',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',31,18,'16',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',31,19,'30',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',31,30,'110',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',31,38,'169',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',31,57,'123',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',31,58,'188',NULL,'북1','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',32,1,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',32,17,'77',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',32,18,'50',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',32,26,'88',NULL,'북9','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',32,27,'11',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',32,30,'101',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',32,38,'133',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',32,39,'78',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',32,57,'199',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',32,58,'241',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',33,1,'153',NULL,'북15','동부청과','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',33,17,'21',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',33,18,'79',NULL,'북11','부산중앙청과','stall',NULL,NULL),
  ('cheonggwamul',33,27,'38',NULL,'북8','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',33,57,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 0, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',33,58,'193',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,1,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,2,'131',NULL,'북15','동부청과','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,3,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,4,'177',NULL,'북15','동부청과','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,5,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,6,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,7,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,8,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,9,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,10,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,11,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,12,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,13,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,14,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,15,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,16,'5',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,17,'73',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,18,'48',NULL,'북11','부산중앙청과','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,19,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,20,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,21,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,22,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,23,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,24,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,25,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,26,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,27,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,28,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,29,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,30,'103',NULL,'북8','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,31,'107',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,32,'136',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,33,'161',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,34,'112',NULL,'북7','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,35,'118',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,36,'179',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,37,'171',NULL,'북6','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,38,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,39,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,40,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,41,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,42,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,43,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,44,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,45,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,46,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,47,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,48,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,49,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,50,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,51,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,52,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,53,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,54,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,55,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,56,NULL,NULL,NULL,NULL,'stall',NULL,'{"b": 1, "l": 0, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',34,57,'299',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 1, "l": 0, "r": 1, "t": 0}'::jsonb),
  ('cheonggwamul',34,58,'113',NULL,'북1','농협반여공판장','stall',NULL,'{"b": 0, "l": 1, "r": 0, "t": 0}'::jsonb),
  ('cheonggwamul',35,2,'131',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',35,3,'117',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',35,4,'271',NULL,'북15','동부청과','stall',NULL,NULL),
  ('cheonggwamul',35,5,'141',NULL,'북14','동부청과','stall',NULL,NULL),
  ('cheonggwamul',35,7,'119',NULL,'북14','동부청과','stall',NULL,NULL),
  ('cheonggwamul',35,31,'107',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',35,32,'136',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',35,33,'161',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',35,34,'112',NULL,'북7','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',35,35,'118',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',35,36,'179',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',35,37,'171',NULL,'북6','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',35,42,'196',NULL,'북5','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',35,45,'191',NULL,'북4','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',35,48,'136',NULL,'북3','농협반여공판장','stall',NULL,NULL),
  ('cheonggwamul',35,57,'231',NULL,'북1','농협반여공판장','stall',NULL,NULL)
) AS v(code, r, c, sn, vn, sect, co, ct, nt, bd)
JOIN public.rn_market_buildings b ON b.code = v.code
ON CONFLICT (building_id, row_idx, col_idx) DO NOTHING;

-- 무배추동 (mubaechu)
INSERT INTO public.rn_market_stalls
  (building_id, row_idx, col_idx, stall_number, vendor_name, section_name, company_name, cell_type, notes, borders)
SELECT b.id, v.r, v.c, v.sn, v.vn, v.sect, v.co, v.ct, v.nt, v.bd::jsonb
FROM (VALUES
  ('mubaechu',1,1,NULL,'무배추동',NULL,NULL,'label',NULL,NULL),
  ('mubaechu',3,1,NULL,'일성상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',3,3,NULL,'울산상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',3,5,NULL,'창녕상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',3,7,NULL,'상주상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',3,9,NULL,'다온유통 조은상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',3,11,NULL,'금정&얌팡',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',3,13,NULL,'좋아농산',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',3,15,NULL,'선우유통',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',3,17,NULL,'영양유통',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',3,19,NULL,'단목상사 가인유통',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',5,1,'231',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',5,3,'226',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',5,5,'236',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',5,7,'252',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',5,9,'263',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',5,13,'264',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',5,15,'253',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',5,17,'122',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',5,19,'227',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',6,1,NULL,'통     로',NULL,NULL,'walkway',NULL,NULL),
  ('mubaechu',7,1,'234',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',7,3,'266',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',7,5,'237',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',7,7,'190',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',7,9,'230',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',7,11,'120',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',7,13,'21',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',7,15,'125',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',7,17,'128',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',8,1,NULL,'나영 상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',8,3,NULL,'안동농산',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',8,5,NULL,'대진상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',8,7,NULL,'천지유통',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',8,9,NULL,'경주상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',8,11,NULL,'참한상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',8,13,NULL,'태백농산',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',8,15,NULL,'부자다 유통',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',8,17,NULL,'옥정팜',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',10,1,NULL,'경북농산',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',10,3,NULL,'반입 신고소',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',10,5,NULL,'도도상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',10,7,NULL,'북천상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',10,9,NULL,'희풍상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',10,11,NULL,'윤씨네 상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',10,13,NULL,'우진상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',10,15,NULL,'영주상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',10,17,NULL,'성보상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',12,1,'228',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',12,5,'217',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',12,7,'198',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',12,9,'216',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',12,13,'222',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',12,15,'225',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',12,17,'104',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',12,19,'219',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',13,1,NULL,'통     로',NULL,NULL,'walkway',NULL,NULL),
  ('mubaechu',14,1,'212',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',14,3,'200',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',14,7,'191',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',14,9,'276',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',14,11,'277',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',14,13,'221',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',14,15,'107',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',14,17,'223',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',14,19,'204',NULL,NULL,NULL,'stall',NULL,NULL),
  ('mubaechu',15,1,NULL,'대림상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',15,3,NULL,'구포상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',15,5,NULL,'동명유통',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',15,7,NULL,'오성상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',15,9,NULL,'신창상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',15,11,NULL,'영동상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',15,13,NULL,'현대상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',15,15,NULL,'철암상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',15,17,NULL,'부산상회',NULL,NULL,'vendor',NULL,NULL),
  ('mubaechu',15,19,NULL,'오륜유통',NULL,NULL,'vendor',NULL,NULL)
) AS v(code, r, c, sn, vn, sect, co, ct, nt, bd)
JOIN public.rn_market_buildings b ON b.code = v.code
ON CONFLICT (building_id, row_idx, col_idx) DO NOTHING;

-- 양념동 (yangnyeom)
INSERT INTO public.rn_market_stalls
  (building_id, row_idx, col_idx, stall_number, vendor_name, section_name, company_name, cell_type, notes, borders)
SELECT b.id, v.r, v.c, v.sn, v.vn, v.sect, v.co, v.ct, v.nt, v.bd::jsonb
FROM (VALUES
  ('yangnyeom',0,0,'12','육일상회','상단',NULL,'stall','구득회',NULL),
  ('yangnyeom',0,1,'11','대영농산','상단',NULL,'stall','박정훈',NULL),
  ('yangnyeom',0,2,'10','시민상회','상단',NULL,'stall','최소은',NULL),
  ('yangnyeom',0,3,'9','반여농산','상단',NULL,'stall','박정일',NULL),
  ('yangnyeom',0,4,'8','동구농산','상단',NULL,'stall','김남진',NULL),
  ('yangnyeom',0,5,'7','부남농산','상단',NULL,'stall','홍선택',NULL),
  ('yangnyeom',0,6,'6','우림푸드','상단',NULL,'stall','이동규',NULL),
  ('yangnyeom',0,7,'5','빅토리농산','상단',NULL,'stall','김현화',NULL),
  ('yangnyeom',0,8,'3~4','경북농산','상단',NULL,'stall','유지수',NULL),
  ('yangnyeom',0,10,'2','마늘나라 생강마을','상단',NULL,'stall','엄대용',NULL),
  ('yangnyeom',0,11,'1','생강마을','상단',NULL,'stall','조미숙',NULL),
  ('yangnyeom',1,0,NULL,'출입구',NULL,NULL,'walkway',NULL,NULL),
  ('yangnyeom',1,9,NULL,'북문',NULL,NULL,'facility',NULL,NULL),
  ('yangnyeom',1,10,NULL,'공동작업장',NULL,NULL,'facility',NULL,NULL),
  ('yangnyeom',2,0,NULL,'기계실',NULL,NULL,'facility',NULL,NULL),
  ('yangnyeom',2,11,NULL,'하역반',NULL,NULL,'facility',NULL,NULL),
  ('yangnyeom',3,0,NULL,'경비실',NULL,NULL,'facility',NULL,NULL),
  ('yangnyeom',4,0,NULL,'차량출입구',NULL,NULL,'walkway',NULL,NULL),
  ('yangnyeom',5,0,'20','함안상회','중간',NULL,'stall','이동현',NULL),
  ('yangnyeom',5,1,'19','동성상사','중간',NULL,'stall','손희경',NULL),
  ('yangnyeom',5,2,'18','금정상사','중간',NULL,'stall','심재택',NULL),
  ('yangnyeom',5,3,'17','남해상회','중간',NULL,'stall','정경자',NULL),
  ('yangnyeom',5,4,'16','양산상회','중간',NULL,'stall','윤만원',NULL),
  ('yangnyeom',5,5,'15','가야농산','중간',NULL,'stall','이수원',NULL),
  ('yangnyeom',5,6,'14','녹원식품','중간',NULL,'stall','최미숙',NULL),
  ('yangnyeom',5,7,'13','예천농산','중간',NULL,'stall','정홍주',NULL),
  ('yangnyeom',5,8,NULL,'화장실',NULL,NULL,'facility',NULL,NULL),
  ('yangnyeom',5,10,NULL,'차량출입구',NULL,NULL,'walkway',NULL,NULL),
  ('yangnyeom',6,0,NULL,'출입구',NULL,NULL,'walkway',NULL,NULL),
  ('yangnyeom',6,11,NULL,NULL,NULL,NULL,'facility',NULL,NULL),
  ('yangnyeom',7,0,'21','맛나라식품','하단',NULL,'stall','이성주',NULL),
  ('yangnyeom',7,1,'22','경주농산','하단',NULL,'stall','한상인',NULL),
  ('yangnyeom',7,2,'23','대일농산','하단',NULL,'stall','곽경민',NULL),
  ('yangnyeom',7,3,'24','영진상회','하단',NULL,'stall','조성권',NULL),
  ('yangnyeom',7,4,'25','영진유통','하단',NULL,'stall','백경옥',NULL),
  ('yangnyeom',7,5,'26','우정농산','하단',NULL,'stall','김태헌',NULL),
  ('yangnyeom',7,6,'27','영양상회','하단',NULL,'stall','김신자',NULL),
  ('yangnyeom',7,7,'28','안동농산','하단',NULL,'stall','장석민',NULL),
  ('yangnyeom',7,8,'29','함양농산','하단',NULL,'stall','임복남',NULL),
  ('yangnyeom',7,9,'30','의성농산','하단',NULL,'stall','박범규',NULL),
  ('yangnyeom',7,10,'31','신풍농산','하단',NULL,'stall','하태순',NULL),
  ('yangnyeom',7,11,'32','한마음농산','하단',NULL,'stall','김선우',NULL),
  ('yangnyeom',7,12,'33','미가농산','하단',NULL,'stall','윤정민',NULL),
  ('yangnyeom',7,13,'34','동천농산','하단',NULL,'stall','권현희',NULL),
  ('yangnyeom',7,14,'35','경북상회','하단',NULL,'stall','이태호',NULL),
  ('yangnyeom',7,15,'36','풍산농산','하단',NULL,'stall','권혁성',NULL),
  ('yangnyeom',7,16,'37','창녕농산','하단',NULL,'stall','오경진',NULL),
  ('yangnyeom',7,17,'38','김해상회','하단',NULL,'stall','이정수',NULL),
  ('yangnyeom',7,18,'39','고추사랑 참깨마을','하단',NULL,'stall','엄현웅',NULL),
  ('yangnyeom',7,19,'40','영산농산','하단',NULL,'stall','신근택',NULL)
) AS v(code, r, c, sn, vn, sect, co, ct, nt, bd)
JOIN public.rn_market_buildings b ON b.code = v.code
ON CONFLICT (building_id, row_idx, col_idx) DO NOTHING;

-- 화훼단지 (hwahwe)
INSERT INTO public.rn_market_stalls
  (building_id, row_idx, col_idx, stall_number, vendor_name, section_name, company_name, cell_type, notes, borders)
SELECT b.id, v.r, v.c, v.sn, v.vn, v.sect, v.co, v.ct, v.nt, v.bd::jsonb
FROM (VALUES
  ('hwahwe',1,0,NULL,'반송로 524',NULL,NULL,'section_header',NULL,NULL),
  ('hwahwe',1,2,NULL,'반송로 560',NULL,NULL,'section_header',NULL,NULL),
  ('hwahwe',1,4,NULL,'반송로 578',NULL,NULL,'section_header',NULL,NULL),
  ('hwahwe',1,6,NULL,'선수촌로 290',NULL,NULL,'section_header',NULL,NULL),
  ('hwahwe',4,0,NULL,'북문입구',NULL,NULL,'section_header',NULL,NULL),
  ('hwahwe',4,2,NULL,'지하철역',NULL,NULL,'section_header',NULL,NULL),
  ('hwahwe',4,4,NULL,'컨테이너',NULL,NULL,'section_header',NULL,NULL),
  ('hwahwe',4,6,NULL,'나무전시장',NULL,NULL,'section_header',NULL,NULL),
  ('hwahwe',5,0,NULL,'부산','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',5,2,NULL,'동성','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',5,4,NULL,'제일천막공사','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',5,6,NULL,'행운','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',6,0,NULL,'만복','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',6,2,NULL,'꽃사랑','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',6,4,NULL,'석대가마솥돼지국밥','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',6,6,NULL,'대자연','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',7,0,NULL,'마산','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',7,2,NULL,'황금','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',7,4,NULL,'예광','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',7,6,NULL,'꽃가람','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',8,0,NULL,'상록','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',8,2,NULL,'꽃마을','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',8,4,NULL,'애천','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',8,6,NULL,'법촌','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',9,0,NULL,'만덕','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',9,2,NULL,'현대','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',9,4,NULL,'녹수','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',9,6,NULL,'동원','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',10,0,NULL,'그린하트','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',10,2,NULL,'청솔','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',10,4,NULL,'자연꽃','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',10,6,NULL,'사랑채','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',11,0,NULL,'삼성','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',11,2,NULL,'해양','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',11,4,NULL,'청림','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',11,6,NULL,'연세','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',12,0,NULL,'창원','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',12,2,NULL,'꽃화원','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',12,4,NULL,'백화','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',12,6,NULL,'들꽃','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',13,0,NULL,'석대','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',13,2,NULL,'코너','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',13,4,NULL,'다래','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',13,6,NULL,'반여','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',14,0,NULL,'수목정','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',14,2,NULL,'푸른화원','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',14,4,NULL,'자연과문화','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',14,6,NULL,'코너','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',15,0,NULL,'유락','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',15,2,NULL,'해양','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',15,4,NULL,'아람화원','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',15,6,NULL,'순란','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',16,0,NULL,'가람','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',16,2,NULL,'청솔','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',16,4,NULL,'이서방','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',16,6,NULL,'꽃누리','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',17,0,NULL,'남우','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',17,2,NULL,'현대','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',17,4,NULL,'푸른','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',17,6,NULL,'청수','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',18,0,NULL,'창선','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',18,2,NULL,'미성','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',18,4,NULL,'코너','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',18,6,NULL,'궁전','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',19,0,NULL,'영남','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',19,2,NULL,'그린','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',19,4,NULL,'미래','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',19,6,NULL,'꽃길','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',20,0,NULL,'서울','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',20,2,NULL,'금복','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',20,4,NULL,'신세계','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',20,6,NULL,'스피드','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',21,0,NULL,'형제','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',21,2,NULL,'수복','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',21,4,NULL,'수림','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',21,6,NULL,'새싹','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',22,0,NULL,'보행자 건널목','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',22,2,NULL,'대동','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',22,4,NULL,'인협','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',22,6,NULL,'영풍','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',23,0,NULL,'밀양','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',23,2,NULL,'백림','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',23,4,NULL,'지하철역 맞은편','반송로 578',NULL,'vendor',NULL,NULL),
  ('hwahwe',23,6,NULL,'무배추동 맞은편','선수촌로 290',NULL,'vendor',NULL,NULL),
  ('hwahwe',24,0,NULL,'대림','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',24,2,NULL,'그린종합','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',25,0,NULL,'한스','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',25,2,NULL,'서울','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',26,0,NULL,'백양','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',26,2,NULL,'봄봄','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',27,0,NULL,'금비','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',27,2,NULL,'서호란','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',28,0,NULL,'성원','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',28,2,NULL,'동산원예','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',29,0,NULL,'영풍','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',29,2,NULL,'초원','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',30,0,NULL,'창호','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',30,2,NULL,'북문 입구','반송로 560',NULL,'vendor',NULL,NULL),
  ('hwahwe',31,0,NULL,'꽃마당','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',32,0,NULL,'에덴','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',33,0,NULL,'고려','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',34,0,NULL,'늘푸른','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',35,0,NULL,'스타다육','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',36,0,NULL,'코너','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',37,0,NULL,'식물나라 선인장','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',38,0,NULL,'석호','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',39,0,NULL,'하동','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',40,0,NULL,'합천','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',41,0,NULL,'신영','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',42,0,NULL,'경북','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',43,0,NULL,'영남','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',44,0,NULL,'부일','반송로 524',NULL,'vendor',NULL,NULL),
  ('hwahwe',45,0,NULL,'상가동 끝부분','반송로 524',NULL,'vendor',NULL,NULL)
) AS v(code, r, c, sn, vn, sect, co, ct, nt, bd)
JOIN public.rn_market_buildings b ON b.code = v.code
ON CONFLICT (building_id, row_idx, col_idx) DO NOTHING;
